version: '3'

services:

 nginx:
   container_name: drash_app_nginx
   build:
     context: .
     dockerfile: .docker/nginx.dockerfile
   volumes:
     - ./src:/var/www/src
   working_dir: /var/www/src
   depends_on:
     - drash
   ports:
     - "8080:80"
   networks:
     - drash-app-network

 apache:
   container_name: drash_app_apache
   build:
     context: .
     dockerfile: .docker/apache.dockerfile
   volumes:
     - ./src:/var/www/src
   working_dir: /var/www/src
   depends_on:
     - drash
   ports:
     - "8080:80"
   networks:
     - drash-app-network

 drash:
   container_name: drash_app_drash
   build:
     context: .
     dockerfile: .docker/drash.dockerfile
   volumes:
     - ./src:/var/www/src
   working_dir: /var/www/src
   ports:
     - "1447:1447"
   command: bash -c "deno run --allow-net app.ts"
   networks:
     - drash-app-network

networks:
 drash-app-network:
   driver: bridge

