name: master

on:
  push:
    branches:
      - master

jobs:
  build:

    env:
      CI: true
      CI_USER_EMAIL: ${{ secrets.CI_USER_EMAIL }}
      CI_USER_NAME: ${{ secrets.CI_USER_NAME }}
      CI_USER_PAT: ${{ secrets.CI_USER_PAT }}

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1

    - name: update long-running branches
      run: |
        console/configure_git
        git pull origin master
        git pull origin staging
        git pull origin production
        git checkout staging && git merge origin/master
        git push
        git checkout production && git merge origin/master
        git push
