name: staging ci

on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      CI: true
      CI_USER_EMAIL: ${{ secrets.CI_USER_EMAIL }}
      CI_USER_NAME: ${{ secrets.CI_USER_NAME }}
      DENO_DRASH_DOCS_ENVIRONMENT: "staging"
      DENO_LATEST_VERSION: "v0.27.0"
      GIT_PUSHER_BOT: ${{ secrets.GIT_PUSHER_BOT }}
      DENO_INSTALL: ="/home/runner/.local"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: |
        npm install

    - name: install deno
      run: |
        curl -fsSL https://deno.land/x/install/install.sh | sh -s $DENO_LATEST_VERSION

    - name: git clone deno-drash
      run: |
        git clone https://github.com/drashland/deno-drash.git ../deno-drash

    - name: make deps.ts from deps.sample.ts
      run: |
        cp deps.sample.ts deps.ts

    - name: compile assets, webpack, and ejs templates
      run: |
        export PATH=$DENO_INSTALL/bin:$PATH
        console/compile_assets
        console/run_webpack --env.environment="$DENO_DRASH_DOCS_ENVIRONMENT"
        console/compile_ejs_templates

    - name: npm run staging
      run: |
        export PATH=$DENO_INSTALL/bin:$PATH
        npm run staging

    - name: commit and push
      run: |
        if [ -z "$(git status --porcelain)" ]; then
          echo "master branch clean"
        else
          git remote rm origin
          git remote add origin https://$GIT_PUSHER_BOT@github.com/drashland/deno-drash-docs.git
          git config user.email $CI_USER_EMAIL
          git config user.name $CI_USER_NAME
          git add staging/*
          git commit -m "npm run staging ($(date))"
          git push origin HEAD:master
        fi
