name: staging

on:
  push:
    branches:
      - staging

jobs:
  build:

    env:
      CI: true
      CI_USER_EMAIL: ${{ secrets.CI_USER_EMAIL }}
      CI_USER_NAME: ${{ secrets.CI_USER_NAME }}
      CI_USER_PAT: ${{ secrets.CI_USER_PAT }}

    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: |
        npm install

    - name: add drashbot
      run: |
        git remote rm origin
        git remote add origin https://$CI_USER_PAT@github.com/drashland/website.git
        git config user.email $CI_USER_EMAIL
        git config user.name $CI_USER_NAME
        git pull origin master

    - name: build staging
      if: github.ref == 'refs/heads/staging'
      run: |
        npm run build:staging

    - name: commit staging
      if: github.ref == 'refs/heads/staging'
      run: |
        git add .
        git commit -m "staging build ($(date))"

    - name: push staging to master
      if: github.ref == 'refs/heads/staging'
      run: |
        git push origin HEAD:master
