name: staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build:

    env:
      CI: true
      CI_USER_EMAIL: ${{ secrets.CI_USER_EMAIL }}
      CI_USER_NAME: ${{ secrets.CI_USER_NAME }}
      DENO_INSTALL: "/Users/runner/.local"
      CI_USER_PAT: ${{ secrets.CI_USER_PAT }}

    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      if: github.event_name == 'push'
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      if: github.event_name == 'push'
      run: |
        npm install

    - name: install deno
      run: |
        console/install_deno

    - name: git clone deno-drash
      run: |
        git clone https://github.com/drashland/deno-drash.git ../deno-drash

    # - name: unit tests
    #   if: github.event_name == 'pull_request'
    #   run: |
    #     export PATH=$DENO_INSTALL/bin:$PATH
    #     console/set_common_env_vars
    #     console/copy_config_files
    #     console/tests

    - name: configure git
      run: |
        console/configure_git

    - name: deploy staging
      if: github.ref == 'refs/heads/staging'
      run: |
        export PATH=$DENO_INSTALL/bin:$PATH
        export DENO_DRASH_DOCS_ENVIRONMENT="staging"
        console/set_common_env_vars
        console/copy_config_files
        console/compile_assets
        console/run_webpack --env.environment=$DENO_DRASH_DOCS_ENVIRONMENT
        console/compile_ejs_templates
        console/staging
        git checkout -- index.html
        git checkout -- public/*
        git add staging/*
        git commit -m "staging build ($(date))"
        git push origin HEAD:master
